[2025-05-14T02:54:43.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-14T02:54:43.366+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_end_to_end.download_dataset manual__2025-05-14T02:54:40.892675+00:00 [queued]>
[2025-05-14T02:54:43.377+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_end_to_end.download_dataset manual__2025-05-14T02:54:40.892675+00:00 [queued]>
[2025-05-14T02:54:43.378+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-14T02:54:43.396+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_dataset> on 2025-05-14 02:54:40.892675+00:00
[2025-05-14T02:54:43.407+0000] {standard_task_runner.py:63} INFO - Started process 338 to run task
[2025-05-14T02:54:43.410+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_end_to_end', 'download_dataset', 'manual__2025-05-14T02:54:40.892675+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp4kl6x6ek']
[2025-05-14T02:54:43.412+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask download_dataset
[2025-05-14T02:54:43.491+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_end_to_end.download_dataset manual__2025-05-14T02:54:40.892675+00:00 [running]> on host 55ce3247436c
[2025-05-14T02:54:43.633+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_end_to_end' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T02:54:40.892675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T02:54:40.892675+00:00'
[2025-05-14T02:54:43.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-14T02:54:43.650+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-14T02:54:43.651+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 20, in download_dataset
    os.makedirs("/data/raw", exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/data'
[2025-05-14T02:54:43.668+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_end_to_end, task_id=download_dataset, execution_date=20250514T025440, start_date=20250514T025443, end_date=20250514T025443
[2025-05-14T02:54:43.682+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task download_dataset ([Errno 13] Permission denied: '/data'; 338)
[2025-05-14T02:54:43.704+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-14T02:54:43.730+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T02:54:43.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
